### ISSUE TITLE
Photobucket ripping has watermarking in 1.7.70, but not 1.7.69

### ISSUE THREAD

**Issue by Cortexmelon** [RipMeApp/ripme#1067]
* Ripme version: 1.7.70

* Java version:  1.8.0_191

* Operating system:  Windows 10 Version 1803

* Exact URL you were trying to rip when the problem occurred: http://s97.photobucket.com/user/jagurl81/library/?sort=3&page=1
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
Photos used to download fine without any photobucket watermark on the downloaded photo in 1.7.69
## Actual Behavior

1.7.70 now downloads the photos with a watermark that photobucket has started to include, however 1.7.69 doesnt if you downgrade.

**Comment by cyian-1756** [comment]
Looks like this is a bug introduced when @PeterSzakacs ported the ripper over to AbstractHTMLRipper

**Comment by PeterSzakacs** [comment]
Just been notified via email.

I checked the image URLs used in the versions compiled from source before my changes and afterward (commit #3a8b875), and they are the same. So I've checked the changes I've made to the code, and while it's just a hunch, I think i might have found it. The old version used the overloaded version of addURLToDownload() which also passed in a referrer and cookies to the url. But the new version passes neither of those, just the image url, prefix and subdirectory. I've also tested downloading a URL using Wget, an the watermark appeared there as well. I didn't notice any watermarks on the albums I tested this ripper with manually and via its (uncommented) unit tests but I guess that was because those weren't included by photobucket back then.

Now, I'm not sure if only the referrer or cookies alone are enough to download without watermark or it needs both. If only cookies, it's a trivial fix, just use the cookies as a member variable set within the getFirstPage() and getNextPage() methods. If it needs the referrer (as well/only) then it will require changing the helper private methods, since in the old version that field seems to be set from a value in the page-embedded JSON containing the image URLs, and the ripper will need to keep track of those values on a per-image URL basis (probably via a hashMap of image URL to values, again as a member variable).

I'm currently trying it out, but I also have some assignments, so... not sure when I can report back if the tested fix works. :man_shrugging:

**Comment by PeterSzakacs** [comment]
Alright guys, I've tested it. 

Apparently, that did the trick. I've tried the same album, and it now downloads images of it without any watermarks. Also I have to correct myself, the referrer is just the URL from which the current Document object (current page) was parsed (so Document::location()) not some value in the embedded JSON. 

In any case, I've commited and pushed the relevant fix. Pull request is here: #1072
