### ISSUE TITLE
xHamster: Not ripping albums from subsequent pages

### ISSUE THREAD

**Issue by rephormat** [RipMeApp/ripme#1087]
* Ripme version:  1.7.70
* Java version: 1.8.0_181
* Operating system: Microsoft Windows [Version 10.0.17134.407]

* Exact URL you were trying to rip when the problem occurred:  https://xhamster.com/users/galaxy10/photos
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

To rip all albums from the first page as well as subsequent pages.

## Actual Behavior

The ripper correctly grabs albums with images from the first page, but fails to get them from subsequent pages.

**Comment by rephormat** [comment]
@cyian-1756 could this be resolved by simply moving the try/catch function for getting the next page out of the while loop?

**Comment by cyian-1756** [comment]
This is happening because when you rip from a users photos you're using quick queue ripping. Instead of operating normally the ripper scans the page for albums it supports and then adds those albums to the queue. To get it to work on multiple pages we'd need to add something like getNextPage

For now however it is possible to use the {x-y} feature to rip all pages. Just enter https://xhamster.com/users/galaxy10/photos/{1-x} into ripme where x is the total number of pages and click rip. Ripme might complain about it being an unsupported url but it will still work

**Comment by cyian-1756** [comment]
I'm closing this as answered
