### ISSUE TITLE
[DeviantART] Prompt to stop ripping when files have been already downloaded

### ISSUE THREAD

**Issue by TjWallas** [RipMeApp/ripme#12]
It would be nice if there is an option to RIP **only** newly added (but not already downloaded) images in a user's favorites.

One way to do that is to stop ripping if a threshold of already downloaded files have been reached instead of continuing to request the files all the way till the end :)

**Comment by rautamiekka** [comment]
Someone actually had the exactly same idea as I did, but I were too afraid to publish it.

A threshold of 3 existing downloads should be good enough IMO.

If we're adding a prompt, it should have a time out in case the user left RipMe to do its job unattended, and if that time out reaches zero, stop ripping the address and move on to the next one.

**Comment by metaprime** [comment]
Or have a threshold and have the "stop ripping" behavior be the default, with a checkbox to force re-ripping the entire set, ignoring the re-rip detection threshold. No prompt necessary.

**Comment by rautamiekka** [comment]
^ Yeah, sounds better.

**Comment by rautamiekka** [comment]
I've got an idea:
1) have an option in the settings to toggle stopping when an already downloaded item is met
2) if step 1 is enabled, begin downloading like normal and keep going until an already downloaded item is met, at which point check the page if there are anything left to download by cross-referencing the links with the existing files. If not, go to the next rip.

The point is there shouldn't be anything left to get when the rest of the page is already downloaded.

**Comment by metaprime** [comment]
Agree with the algorithm, but it only works for sites where new content is added to the start of the feed we rip from, and no new content is added in the middle.

Something to consider here: this wouldn't necessarily work the same way on all sites. Imgur albums could have new images added to the middle. Some websites add new content at the end (you'd start a re-rip, and visit all of the oldest content before getting to the new content -- consider a comic website like xkcd where a rip could start at comic 1. Some sites may not have a concept of "start from the end" because you start from the first page and work your way forward until there's nothing left (sites which let you search by tag).

At a minimum, this needs to be opt-out (or opt-in) per-ripper. It only makes sense sometimes.

**Comment by rautamiekka** [comment]
^ Yes, not an universal solution. I know DeviantArt, Inkbunny and FurAffinity work this way (on DA the order in the folder can be changed manually afterwards), and Tumblr probly doesn't have any other options than oldest first AFAIS.

**Comment by cyian-1756** [comment]
> It would be nice if there is an option to RIP only newly added (but not already downloaded) images in a user's favorites.

This can be achieved on any site by clicking the "Remember URL history" check box in the configure menu. It will make ripme remember and skip any already downloaded image URLs
