### ISSUE TITLE
Quarantined subreddits cannot be downloaded

### ISSUE THREAD

**Issue by TomArrow** [RipMeApp/ripme#1245]
* Ripme version: 1.7.80
* Java version: java version "1.8.0_202"  Java(TM) SE Runtime Environment (build 1.8.0_202-b08)                           Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
* Operating system: 6.1 Build 7601 Service Pack 1
* Exact URL you were trying to rip when the problem occurred:  https://www.reddit.com/r/OffensiveMemes/
* Please include any additional information about how to reproduce the problem: Just try ripping it.

## Expected Behavior
It would rip normally.

## Actual Behavior
It says "Rip complete, saved to G:\Backup\ripme reddit image downloader\rips\reddit_sub_OffensiveMemes
Failed to load https://www.reddit.com/r/OffensiveMemes.json after 1 attempts"
No images are downloaded.

This is most likely because the subreddit is "quarantined" and requires the user to acknowledge the warning before one can proceed to the sub.

I tried it both with and without the / slash at the end of the URL, it makes no difference.

The same happens with other quarantined subs like r/CringeAnarchy

**Comment by Gamerick** [comment]
Quick look at this shows me that this would not be a simple fix. Because of the way we access reddit we don't (and can't) get that confirmation dialog so in it's current state the code simply will not be able to access quarantined subreddits. 

To be more technical, we would have to add support for people being able to login to reddit via RipMe. This would be a very significant update so I'm going to open a new request to keep track of that
