### ISSUE TITLE
Feature request: InstagramRipper - Add upload date and time to the start of the filename

### ISSUE THREAD

**Issue by ULBAZOR** [RipMeApp/ripme#138]
Every image and video uploaded to Instagram has an upload date and time. Here is an example: https://imgur.com/wiFijtd
At the moment the InstagramRipper does not sort the ripped files in any way, it simply just rips them and saves them as they are already named, which is just a sequence of numbers, letters and underscores. Unfortunately this leads to the folders of the ripped files being unsorted and unorganized. If someone could upgrade the InstagramRipper so it retrieves the upload dates and times of the files and adds them to the start of the filenames when it saves them (like this for example: https://imgur.com/ODppHlS) it would make the InstagramRipper so much better than it is right now. I and many others would appreciate it a lot.

**Comment by tehloxely** [comment]
I would love this.

**Comment by cyian-1756** [comment]
With the last rewrite of the IG ripper this should be pretty easy to do. Just decode the date field of the json data (No idea what format it's in) and add it as the file name in the call to `addURLToDownload`

**Comment by cyian-1756** [comment]
I made a PR that adds this, it should be in version 1.6.11

**Comment by poiuyrt546** [comment]
Is there a way to disable this? 
It's re-ripping ALL the existing files with the new save file format, which leads to duplication.

**Comment by metaprime** [comment]
The new functionality to remember already-ripped urls (rather than by matching filename saved on disk) should help with this kind of problem in the future. Probably the safest way to deal with duplication while this data is populated is to add a file-hash-based de-duplication mechanism (as an optional checkbox) to check the hashes of all items in the folder at the end of a rip, and remove duplicates.
