### ISSUE TITLE
Ripme only use AppData Folder

### ISSUE THREAD

**Issue by revanwolf** [RipMeApp/ripme#152]
* Ripme version: >1.5.14
* Java version: 1.8.0_151
* Operating system: Windiws 7 7601
* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The app use the history.json and rip.properties from the folder of Ripme.jar.

## Actual Behavior

The app use the "AppData/Local" Folder, rendering multiple instances(i use different folder for different type of content) of the app impossible.

**Comment by cyian-1756** [comment]
Damn, I didn't think anyone relied on that behavior. Does the rip.properties need to be different in each folder? Because if not I can just add a config option to use the history.json/url_history.txt from the same dir as ripme

**Comment by rautamiekka** [comment]
^ While you're at it, I'm thinking you could introduce a portable mode which uses `ripme_portable.properties` first if it exists in the same folder, otherwise the system-specific one. The format of the portable config would be identical.

The idea borrowed from GZDoom code which referenced a `_portable.ini`.

**Comment by sxnfxsed** [comment]
I have the same problem, I just copy the history and properties files in to the AppData folder everytime I use a different collection but it would be great to have an option to use the history that's in the same folder as the jar

**Comment by cyian-1756** [comment]
I think the best soluation to this would be to add a "portable mode" check box that used the files in the same dir as ripme instead of the system ones.

If anyone has some know how when it comes to java guis I could use a hand with this, because the config page of ripme is pretty well full at this point (We're going to need more pages or something like that)

**Comment by revanwolf** [comment]
Unfortunately i use different folder so the rip.properties is different.

**Comment by cyian-1756** [comment]
@revanwolf Ripme 1.6.9 has the ability to run ripme in portable mode, which will use the history.json and rip.properties from the same folder as ripme.jar. To use portable mode just copy rip.properties to the same dir as ripme.jar and start the jar
