### ISSUE TITLE
Add cookies support for Luscious

### ISSUE THREAD

**Issue by aeruower** [RipMeApp/ripme#1657]
* Ripme version: 1.7.92
* Java version: java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
* Operating system: Microsoft Windows [Version 10.0.18363.836]

* Exact URL you were trying to rip when the problem occurred (NSFW): https://members.luscious.net/albums/star_tri_gan_one_347045/
* Please include any additional information about how to reproduce the problem: This problem occurs during any attempt to download any album from categories restricted to members _only_, such as "Private to Luscious", which is the mentioned URL's category.

## Expected Behavior

I paste the URL into the URL input box, click on "Rip", RipMe successfully downloads the album.

## Actual Behavior

I paste the URL into the URL input box, click on "Rip", RipMe attempts to download the album and throws this error: 

`Failed to load https://old.luscious.net/albums/star_tri_gan_one_347045/: Status Code 403. You might be able to circumvent this error by setting cookies for this domain`

**Comment by A-Sparowe** [comment]
It's weird because luscious.net is literally the site I have the most luck downloading from and the one that's never given me any problems. I'll have to check later tonight, most likely tomorrow morning when I have time. I'll look over my settings for that site and the few others I use. Mostly anime/hentai sites. I literally just found out today after replying to your comment that ripme supports all sorts of sites and not just anime/hentai ones lol.

I have the hardest time downloading from Pixiv and sankakucomplex, but I believe I read in the issues section it was removed due to the owner of that site continually making it harder on the ripme devs by adding in features that prevent downloaders. I mean that site is still one of my favorites, but it's slowly going to shit. Constant adds and even just casually browsing I get "you're making too many requests" messages now. Seems the owner of the site has decided to start cashing in on making money off of other artists' work and charging people for premium accounts now to get rid of adds. I've already started noticing more and more "well known" artists requesting their stuff being taken down followed by them either being banned by the owner or requesting a ban. I'm all for helping out artists if and when I have money so more power to them.

**Comment by A-Sparowe** [comment]
Ok, so I would check your "Customize Filters" options on luscious. Check the box for "Private to Luscious" so that the site knows you want to see that content. Also, make sure it's unchecked from the list below that. The list below is the content you want to be blocked from your dashboard. That's about all I can say to try. Maybe try making an account and logging in while you download using ripme? Other than that I couldn't possibly know what is causing it to fail. I would assume it's the options in the "customize filters" settings menu. I haven't tried it yet myself but if you're still having problems I can edit a filter and try it to see if it works for me. I'd like to keep blocking the content I already have set to be blocked. I wasn't blocking the "Private to Luscious" tag so I don't know for sure if maybe I've already downloaded from it before or not.

**Comment by aeruower** [comment]
Thank you for your replies. If it helps you in any way, here is this wonderful and simple Luscious downloader I found written in Python:
https://github.com/Lucas8x/luscious-downloader

Every album I tried to download so far worked. Here or there happens a few files couldn't be downloaded, but it logs them in "logs.txt" so you can easily extract any URLs in that log file. In case of any issues, you can create a new bug report in that repository.

Have a nice day

~aeruower

**Comment by aeruower** [comment]
I didn't have that category (Private to Luscious) blocked. I tried it with other by-default-blocked categories, was logged in, had no success.

**Comment by asl97** [comment]
@aeruower did the genetic cookie support added by #1483 not work for you?

**Comment by aeruower** [comment]
I forgot to respond.

After some hassle with cookies, it worked. Awesome feature, thanks. Closing.
