### ISSUE TITLE
furaffinity login broken

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#175]
furaffinity has added a captcha to their login page, the ripper will have to be rewritten to either use user provided cookies or to not have to login

Login page: https://www.furaffinity.net/login/?ref=https://www.furaffinity.net/gallery/mustardgas/

**Comment by rautamiekka** [comment]
JDownloader can get through it, so RipMe can too.

**Comment by cyian-1756** [comment]
Question, why does the FA ripper even need to login? Looking over some random FA albums ripme can download them fine without logging in

**Comment by rautamiekka** [comment]
^ Since it's not mandatory (AFAIK) even when your gallery is NSFW or questionable, I think it's just out of courtesy.

Another could be to make automatic ripping harder.

For example https://www.furaffinity.net/user/higgly.town.hero/ makes some sense (some straight-up porn, a bit of drug usage, some fucked up talking) to be restricted away from public view, but I dropped him a question why he did so.

**Comment by cyian-1756** [comment]
> JDownloader (Open Source) can get through it, so RipMe can too.

Can you point to the code were JDownloader does that? Grepping the source code doesn't come up with anything about furaffinity

**Comment by cyian-1756** [comment]
as of 1.7.9 ripme uses cookies to auth and doesn't need to login
