### ISSUE TITLE
Ability to Disable Downloading Images Older Than Last Rip

### ISSUE THREAD

**Issue by Davrial** [RipMeApp/ripme#18]
I have downloaded a lot of albums at this point, and I frequently use the "Re-Rip Checked" option to download new content in said albums. The problem is, if there are any images in the albums that I delete (mostly filler images, thumbnail versions, etc), they all get re-downloaded when I re-rip.

So my suggestion (slash question as to if it's even possible) is as what the title says: Would it be possible to add a check/toggle option to disable the downloading of files older than the last rip, specifically when re-ripping albums? That may or may not even make the re-ripping even faster, as it would force it to skip over images older than set date/time, which would mean it wouldnt have to check if a file has already been downloaded.

**Comment by rautamiekka** [comment]
Unless someone has a better idea, that'd mandate using a file containing the links to the previously downloaded files. For example: https://github.com/rg3/youtube-dl/ can use a file which lists the vid IDs of already fetched vids -after- you DL, which is way easier to implement and use compared to a general pic ripper.

The JSON format I can imagine right now that'll enable matching multiple items from a single address:
```json
{
    "ORIGINAL LINK SUCH AS FOLDER OR ALBUM": {
        "ITEM IN FOLDER OR ALBUM": [
            "DOWNLOAD LINK USED",
            ...
        ], ...
    }, ...
}
```

For example:
```json
{
    "http://rautamiekka.deviantart.com/gallery/?catpath=/": {
        "http://rautamiekka.deviantart.com/art/Princess-Luna-BIG-COLLAB-colored-0-672156533": [
            "http://img09.deviantart.net/ed89/i/2016/335/4/2/_sleeping_on_the_job___finnish_by_rautamiekka-daq4v9l.png"
        ]
    }, ...
}
```

That allows for very fine (by folder/album address, item address in the folder/album, the DL link used, the filename used) matching of already-downloaded content, assuming the same format works for everything.

Otherwise we'll need ripper-specific formats built into the specific ripper and an unified API to use the format.

**Comment by tehloxely** [comment]
Having this addition to the app would drastically reduce download times.

**Comment by rautamiekka** [comment]
^ Re-download times, mind you.

**Comment by Davrial** [comment]
^ *Re-RIP times, mind you. It would be explicitly _preventing_ re-_downloads_

**Comment by metaprime** [comment]
@rautamiekka That's exactly the solution I imagined. This request has been opened and discussed multiple times in the past, and at least one of those issues is open (probably aggregating links to the duplicates as well).

**Comment by anonCoder123** [comment]
I support this enhancement as well. I opened an issue for deduplication a week or two ago, but it got closed since "ripme doesn't have deduplication by design".

**Comment by metaprime** [comment]
@anonCoder123 This is a distinct issue from deduplication. This is an issue of not downloading URLs already downloaded. It mostly solves the problem of deduplication (except for duplicates downloaded from different URLs)

**Comment by rautamiekka** [comment]
@Davrial Do you mind explaining the 'confused' reaction to my comment that proposes a JSON link storage format ?

**Comment by cyian-1756** [comment]
This was added, to use it click the "Remember URL history" button in the config menu
