### ISSUE TITLE
RipMe doesn't work anymore

### ISSUE THREAD

**Issue by GreATMaN80** [RipMeApp/ripme#1806]
* Ripme version: from 1.7.93 and 1.7.94
* Java version: build 1.8.0_271-b09
* Operating system: macOS Big Sur

Hello, 
I've got problem with RipMe. I tried to download from Reddit and other site but the software doesn't stat. I put the URL and click on RIP and nothing happen... This is for all URL and website i try.

Is this from Java or RipMe?

**Comment by FROZYO** [comment]
Same here, also on Big Sur!

**Comment by therealdbt** [comment]
Also have this problem since early November. Also since updating to Big Sur.

Have we figured anything out yet?

I've attached photos of just before hitting "Rip" and just after. It just sits there doing nothing.

<img width="452" alt="Screen Shot 2020-12-26 at 11 18 30 AM" src="https://user-images.githubusercontent.com/76623574/103155289-58653580-476c-11eb-9bc0-ca87871d5ba3.png">
<img width="454" alt="Screen Shot 2020-12-26 at 11 18 44 AM" src="https://user-images.githubusercontent.com/76623574/103155290-5ac78f80-476c-11eb-8caa-2525b7454eba.png">

**Comment by jimbro193** [comment]
I'm experiencing this as well.

RipMe version: 1.7.94
Java version: build 1.8.0_271-b09
OS: macOS Catalina version 10.15.7

**Comment by FROZYO** [comment]
Any updates on this?

**Comment by soloturn** [comment]
seems to be big sur, maybe try to install java-15:
https://dev.to/pablohs1986/macos-users-java-problems-in-big-sur-help-7pa

here some other hints which point towards the big sur java install:
https://stackoverflow.com/questions/64062444/change-java-version-in-macos-bigsur 

this ripme binary is tested with java-8, and java-15, we do not test java-11, but it should work:
https://github.com/ripmeapp2/ripme/actions/runs/523129601

**Comment by FROZYO** [comment]
I can't seem to get it to work despite installing Java-15

**Comment by 007hacky007** [comment]
The problem is in the disk permissions. In order to fix this, go to the System Preferences -> Security -> Privacy -> Full Disk Access, press "+" and add `/System/Library/CoreServices/JavaLauncher.app`

After that, it should work.

**Comment by GreATMaN80** [comment]
Thank you so much!!!! Work again
it was so simple but you had to think about it!
