### ISSUE TITLE
Ripme stuck on 15.7 and needs to update every time I open it.

### ISSUE THREAD

**Issue by Smoreonastick** [RipMeApp/ripme#219]
* Ripme version: 15.7 
* Java version:   "1.8.0_151"
* Operating system:  Win 10 x64

**Comment by cyian-1756** [comment]
Have you tried downloading the lastest version of ripme from the release section here on github?

**Comment by metaprime** [comment]
Sounds like the update mechanism is failing for some reason. Maybe it is failing to download the update, maybe the script to update you to the new version of the app is not running. We might be able to help if you gave us more information, but the likely fix is to just manually download the latest version.

Since we haven't changed the updater code, I'd suspect your problems with updating will persist even after you manually update. If so, we can continue trying to get more info about the problem and see if there's anything we can do to fix it.

**Comment by cyian-1756** [comment]
@Smoreonastick  Is this still an issue?

**Comment by rephormat** [comment]
@cyian-1756 no response from author.  Recommend closing.
