### ISSUE TITLE
tumblr download doesnt work

### ISSUE THREAD

**Issue by 4Schatten** [RipMeApp/ripme#321]
any ideas what i am or the software is doing wrong ? 
it happend with all tumblr links
<img width="795" alt="screenbang1" src="https://user-images.githubusercontent.com/34244208/33561297-944c33f8-d912-11e7-8500-c076c907b87a.png">

thank you

**Comment by wurlii** [comment]
Same here since about two weeks now.

In addition, if the rip is started again (with the same URL or by Re-rip checked command), the ripper reports that the files already exist.
If url_history.txt is removed, the error messages in previous post is displayed again (can be repeated infinit often ;)).

Please fix the general error behaviour in relation also to "new" url_history.txt file. Seems the sync is not correct.

**Comment by cyian-1756** [comment]
This was fixed in 1.7.8
