### ISSUE TITLE
Ripme does not rip Aerisdies.com doujin

### ISSUE THREAD

**Issue by bloggingninja** [RipMeApp/ripme#335]
* Ripme version:
* Java version: 1.8.0-144
* Operating system: winver 10
* Exact URLs you were trying to rip when the problem occurred: http://www.aerisdies.com/html/lb/douj_5230_1.html
http://www.aerisdies.com/html/lb/douj_s141.html
* Please include any additional information about how to reproduce the problem:
enter either of the above into RipMe and the below problem happens.

## Expected Behavior

Expected ripme to download the doujin album like it does from the gallery.

## Actual Behavior

a blank line shows up in the log and nothing happens

**Comment by cyian-1756** [comment]
Looking at the logs the debug output is 

Found album ripper: com.rarchives.ripme.ripper.rippers.AerisdiesRipper
Found album ripper: com.rarchives.ripme.ripper.rippers.AerisdiesRipper
Could not find ripper for URL http://www.aerisdies.com/html/lb/douj_s141.html

It might be because the url doesn't match the regex in getGID, but if that was it I'd expect it to throw a MalformedURLException

Do other Aerisdies links fail or only the doujin?

**Comment by bloggingninja** [comment]
it seems like only the doujin fail to download anything. everything else seems to download fine except for the animated gifs category (which downloads the jpgs but not the gifs.)
