### ISSUE TITLE
Provide a way to verify download file

### ISSUE THREAD

**Issue by WPFilmmaker** [RipMeApp/ripme#337]
I can't see anywhere on the page a way to verify the download. A sha256sum or gpg would be nice.

**Comment by rautamiekka** [comment]
The title makes it sound like you want the ripping to be verified, but you want to verify you downloaded RipMe correctly.

**Comment by cyian-1756** [comment]
> A sha256sum or gpg would be nice.

That is something that should be done and added to ripmes built in updater. It shouldn't be hard to have ripme check the file sum before installing a new version

**Comment by WPFilmmaker** [comment]
@rautamiekka apologies for the not very clear title.
@cyian-1756 That would be great!

**Comment by cyian-1756** [comment]
I'm the best way to do this would be adding the file hash to https://github.com/RipMeApp/ripme/blob/master/ripme.json and having patch.py adding the file hash for every new version, in a format like
`hashs: [ $version_number: $hash]` which will be updated with every new version.

**Comment by rautamiekka** [comment]
^
>hashs

-> `hashes` for correctness.

**Comment by WPFilmmaker** [comment]
@cyian-1756 sounds like a great idea! A question regarding automatic updates, are the updates send from a server? Is there any way you use to avoid someone hijacking the release and send malicious code with an upgrade? Thank you for the great project.

**Comment by cyian-1756** [comment]
> A question regarding automatic updates, are the updates send from a server?

The updates come from github over https

> Is there any way you use to avoid someone hijacking the release and send malicious code with an upgrade?

To do that they'd need to MITM your connection and downgrade you to http and point you at their own server with a malicious version of ripme, adding hashes won't stop this attack because if someone can MITM you they can replace the hash ripme checks against with any hash they want.

To stop an attack like that ripme could start signing it's releases using gpg, but the end user would have to verify the signature because including a gpg lib in ripme would blow up the file size

Another way around this (At least for linux users) would be to get ripme into the repos of a few popular distros, however most distros have a code freeze at some point or a rather long vetting process meaning that the version of ripme in the repos would almost always be outdated.

**Comment by WPFilmmaker** [comment]
@cyian-1756 Thank you for the explanation!
Indeed having repos for each main distro would be a lot of work, but regarding the gpg, most of the software that provide such verification (like Firefox) simply add a gpg sig file which you can then download separately and verify by yourself through command line?(Both on Windows and Linux),  I wasn't aware that you had to increase the file size.
Regardless thank you again for the work you put on ripme and for any solution you will adopt to make it safer!

**Comment by cyian-1756** [comment]
> most of the software that provide such verification (like Firefox) simply add a gpg sig file which you can then download separately and verify by yourself through command line?

Yup that is how most software does it.

>  I wasn't aware that you had to increase the file size.

That only happens if you're checking the sig from the program itself. If you make the user do it (like how firefox does it) there's no change in file size

> Regardless thank you again for the work you put on ripme and for any solution you will adopt to make it safer!

I'm thinking file hashes and maybe signing the binaries @metaprime what do you think?
