### ISSUE TITLE
[Request] Support for erome.com

### ISSUE THREAD

**Issue by tehloxely** [RipMeApp/ripme#36]
Since eroshare is gone, I would love to see support for erome.com.

**Comment by cyian-1756** [comment]
Can you post a video link?

**Comment by metaprime** [comment]
Included in #29

**Comment by metaprime** [comment]
https://www.erome.com/a/ixVfLNtQ

**Comment by cyian-1756** [comment]
> Direct links (might be helpful to support in case of reddit users linking directly):

I say put the direct links in their own ripper (erome seems to link to the actual file and not a web page)

>  https://s2.erome.com/1/5S5SFldM/mPJG0oPA.mp4 -- video link

For whatever reason that url is returning 405 not allowed

**Comment by rautamiekka** [comment]
>> https://s2.erome.com/1/5S5SFldM/mPJG0oPA.mp4 -- video link

>For whatever reason that url is returning 405 not allowed

Same for me and I've never been on erome or eroshare -and- the erome links open in browser just fine except for that one, so if it's an IP range ban it's an exaggerated one, but I'm confident there's no ban in effect. If erome has any private/public systems for uploads, that's the viable reason for the `405 NOT ALLOWED`, otherwise it's a dead link.
