### ISSUE TITLE
8muse rerip does not work

### ISSUE THREAD

**Issue by Oni1314** [RipMeApp/ripme#453]
* Ripme version: 1.7.22
* Java version: java 8
* Operating system: Win7 home -->
https://www.8muses.com/comics/album/Various-Authors/Sillygirl/The-Girly-Watch/Issue-6

## Expected Behavior
I reipped the url:
https://www.8muses.com/comics/album/Various-Authors
then I tried to rep the url:
https://www.8muses.com/comics/album/Various-Authors/Sillygirl
in a seperate folder
and I expeckt to get a new folder with the images

## Actual Behavior
It gives me an empty folder withe the path 8muses_The_Girly_Watch_Issue_6
and does not update new pictures
it tells me:
and it tells me:
Already downloaded https://www.8muses.com/image/fm/Gk+ZFU2KOdtUyDNqLrqO+82R+2mh8CaZ4tah6Du3-FuOrJVqOITUxV8oWec1Lr4y01tj5F-Xs0nqw0bKWW93jYCIFCV0nag7l0PGQkph9WX7eu6uYd8f3HyfjjYbuCwo.jpg

**Comment by Oni1314** [comment]
I tried it with *overwrite existing files* in Option checked and unchecked.
Can you give an option in the menu to *force download again*?

**Comment by cyian-1756** [comment]
> and it tells me:
Already downloaded https://www.8muses.com/image/fm/Gk+ZFU2KOdtUyDNqLrqO+82R+2mh8CaZ4tah6Du3-FuOrJVqOITUxV8oWec1Lr4y01tj5F-Xs0nqw0bKWW93jYCIFCV0nag7l0PGQkph9WX7eu6uYd8f3HyfjjYbuCwo.jpg

This is expected behavior. By default ripme skips files it has downloaded in pervious rips. To change this behavior go to the configuration tab and uncheck "Remember URL History"
