### ISSUE TITLE
Add --version, -v arguments to CLI

### ISSUE THREAD

**Issue by metaprime** [RipMeApp/ripme#49]

**Comment by arvchristos** [comment]
Is this necessary? Whenever the app is launched it prints this string among others:
`Initialized ripme vX.Y.Z`
Do you think the app should print something else?

**Comment by rautamiekka** [comment]
^ **_NOTE: Talking about NIX systems in this comment, the procedure is different on Window$ ..._**

Starting RipMe with a version flag would allow to more easily check RipMe's version when you don't need to read much text; the reading can be stopped at EOF or EOL, of which EOF is far easier. Otherwise, actually, it'll be pretty hard to check RipMe's version; you have to
- provide a bogus address and read RipMe's output until you get the init line, or redirect the output to a and parse the file.
- extract and parse the file `META-INF/MANIFEST.MF` from the JAR, which has `Specification-Version: 1.5.7` and `Implementation-Version: 1.5.7` lines, with those being for RipMe 1.5.7.
- as the closest and second best way, use the `--help` flag and read the first row, which is always done by EOL.

All of that requires `grep --extended-regex` support, which allows using `egrep` as a shortcut, or `grep --perl-regexp`. Just realized I've used the ERE version all the time without realizing I should be using the Perl one since that's the RegEx flavor I'm used to, which is why some REs have failed ...

So, yeah, a version flag would be useful.

**Comment by arvchristos** [comment]
@rautamiekka I've implemented the -v flag result that prints only the version number. I think this is what you meant. 

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
